"""
forecaster/train.py

Offline supervised training for `SmartKeyForecaster` (PLAN.md
Addition A). Owned by Person A (split.md §1).

MSE loss for the pool head, cross-entropy loss for the threat head.
Trained on rollouts generated by *baseline* policies
(`agents/baselines.py`) across S1-S4 seeds -- never on `rl_experiment_*`
logs (Datasets & Provenance) and never end-to-end with the DQN (frozen
once trained; PLAN.md Addition A unit test: "no gradient flow from DQN
loss into forecaster").
"""

from __future__ import annotations

from pathlib import Path

from forecaster.dataset import build_datasets
from forecaster.model import SmartKeyForecaster


def train(
    rollout_log_paths: list[Path],
    checkpoint_out: Path,
    epochs: int = 50,
    lr: float = 1e-3,
) -> dict[str, float]:
    """Train a `SmartKeyForecaster`, save the checkpoint, and return
    final train/val metrics (threat cross-entropy, pool-head MSE per
    horizon)."""
    raise NotImplementedError


if __name__ == "__main__":
    raise NotImplementedError
