"""
forecaster/train.py

Offline supervised training for `SmartKeyForecaster` (PLAN.md
Addition A). Owned by Person A (split.md §1).

MSE loss for the pool head, cross-entropy loss for the threat head.
Trained on rollouts generated by *baseline* policies
(`agents/baselines.py`) across S1-S4 seeds -- never on `rl_experiment_*`
logs (Datasets & Provenance) and never end-to-end with the DQN (frozen
once trained; PLAN.md Addition A unit test: "no gradient flow from DQN
loss into forecaster").

Run it:

    .venv/bin/python -m forecaster.train
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

from experiments.train import load_full_config
from forecaster.dataset import (
    build_datasets,
    collect_rollouts,
    train_validation_split,
)
from forecaster.model import SmartKeyForecaster

DEFAULT_CHECKPOINT = "checkpoints/forecaster.pt"


@dataclass
class ForecasterTrainingRecord:
    train_losses: list[float] = field(default_factory=list)
    validation_losses: list[float] = field(default_factory=list)
    threat_accuracies: list[float] = field(default_factory=list)
    threat_balanced_accuracies: list[float] = field(default_factory=list)
    pool_mae: list[float] = field(default_factory=list)
    n_train_samples: int = 0
    n_validation_samples: int = 0
    checkpoint_path: str | None = None


def train_forecaster(
    config: dict[str, Any] | None = None,
    epochs: int = 12,
    batch_size: int = 128,
    learning_rate: float = 1e-3,
    pool_loss_weight: float = 1.0,
    rollout_steps: int = 1200,
    rollout_seeds: tuple[int, ...] = (0, 1),
    checkpoint_path: str = DEFAULT_CHECKPOINT,
    seed: int = 0,
    verbose: bool = True,
) -> tuple[SmartKeyForecaster, ForecasterTrainingRecord]:
    """Collect baseline rollouts, build the sliding-window dataset, and
    train both heads jointly.

    The two losses are summed rather than trained in alternation, with
    `pool_loss_weight` available to rebalance them. They share an
    encoder, so joint training is what makes the shared representation
    useful to both -- and the pool head's regression targets are on a
    much smaller numeric scale than the cross-entropy term, which is why
    the weight exists as a knob rather than being hardcoded to 1.
    """
    config = config if config is not None else load_full_config()
    torch.manual_seed(seed)

    if verbose:
        print("collecting baseline rollouts (S1-S4) ...", flush=True)
    logs = collect_rollouts(config, n_steps=rollout_steps, seeds=rollout_seeds)
    windows, threat_targets, pool_targets = build_datasets(logs)

    (train_x, train_threat, train_pool), (val_x, val_threat, val_pool) = train_validation_split(
        windows, threat_targets, pool_targets, seed=seed
    )

    record = ForecasterTrainingRecord(
        n_train_samples=int(train_x.shape[0]),
        n_validation_samples=int(val_x.shape[0]),
    )
    if verbose:
        print(
            f"  {record.n_train_samples} train / {record.n_validation_samples} validation samples "
            f"from {len(logs)} rollouts"
        )

    model = SmartKeyForecaster()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    threat_loss_fn = nn.CrossEntropyLoss(weight=class_weights_for(train_threat))
    pool_loss_fn = nn.MSELoss()

    n_samples = train_x.shape[0]
    for epoch in range(1, epochs + 1):
        model.train()
        permutation = torch.randperm(n_samples)
        epoch_loss = 0.0
        n_batches = 0

        for start in range(0, n_samples, batch_size):
            batch_idx = permutation[start : start + batch_size]
            batch_windows = train_x[batch_idx]
            batch_threat = train_threat[batch_idx]
            batch_pool = train_pool[batch_idx]

            threat_logits, pool_outputs = model(batch_windows)

            # cross-entropy wants (N, C, ...) with class indices as targets
            threat_loss = threat_loss_fn(threat_logits.transpose(1, 2), batch_threat)
            pool_loss = pool_loss_fn(pool_outputs, batch_pool)
            loss = threat_loss + pool_loss_weight * pool_loss

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()

            epoch_loss += float(loss.item())
            n_batches += 1

        record.train_losses.append(epoch_loss / max(1, n_batches))

        metrics = evaluate_forecaster(model, val_x, val_threat, val_pool, pool_loss_weight)
        record.validation_losses.append(metrics["loss"])
        record.threat_accuracies.append(metrics["threat_accuracy"])
        record.threat_balanced_accuracies.append(metrics["threat_balanced_accuracy"])
        record.pool_mae.append(metrics["pool_mae"])

        if verbose:
            print(
                f"  epoch {epoch:2d}  train {record.train_losses[-1]:.4f}  "
                f"val {metrics['loss']:.4f}  threat_acc {metrics['threat_accuracy']:.3f}  "
                f"balanced {metrics['threat_balanced_accuracy']:.3f}  "
                f"pool_mae {metrics['pool_mae']:.4f}"
            )

    model.save(checkpoint_path)
    record.checkpoint_path = checkpoint_path
    if verbose:
        print(f"saved forecaster checkpoint to {checkpoint_path}")

    return model, record


def class_weights_for(threat_targets: torch.Tensor) -> torch.Tensor:
    """Inverse-frequency class weights for the threat head's loss.

    WHY THIS IS NECESSARY, not a thumb on the scale. Threat posture is
    severely imbalanced -- measured 45,293 / 6,688 / 144 across the three
    classes -- because escalation is by construction a rare event. Under
    unweighted cross-entropy the head collapsed onto the majority class
    completely: per-class recall 1.000 / 0.001 / 0.000, balanced accuracy
    0.334, which for three classes is *exactly* chance.

    Raw accuracy hid this. It read 0.838, which looks like a working
    classifier and is in fact the majority-class rate: a model that
    answers "calm" to everything scores the same. Reporting balanced
    accuracy alongside it is the fix for the *measurement*; weighting
    the loss is the fix for the *training*.

    Inverse frequency, normalised to mean 1 so the threat term keeps its
    existing scale relative to the pool term and `pool_loss_weight` does
    not silently change meaning.
    """
    counts = torch.bincount(threat_targets.flatten())
    counts = torch.clamp(counts, min=1)  # never divide by zero on an absent class
    weights = counts.sum() / counts
    return weights / weights.mean()


def balanced_accuracy(predicted: torch.Tensor, targets: torch.Tensor) -> float:
    """Mean per-class recall -- chance is 1/n_classes regardless of how
    skewed the data is, which is what raw accuracy fails to be here."""
    recalls = []
    for class_index in range(int(targets.max().item()) + 1):
        mask = targets == class_index
        if mask.sum() == 0:
            continue
        recalls.append(float((predicted[mask] == class_index).float().mean().item()))
    return float(sum(recalls) / max(1, len(recalls)))


def evaluate_forecaster(
    model: SmartKeyForecaster,
    windows: torch.Tensor,
    threat_targets: torch.Tensor,
    pool_targets: torch.Tensor,
    pool_loss_weight: float = 1.0,
) -> dict[str, float]:
    """Validation metrics. Reported per epoch so a null result is
    visible early: if `threat_accuracy` never beats the majority-class
    rate, the threat head has learned nothing and the E-A ablation
    should be expected to come out flat."""
    model.eval()
    with torch.no_grad():
        threat_logits, pool_outputs = model(windows)
        threat_loss = nn.functional.cross_entropy(threat_logits.transpose(1, 2), threat_targets)
        pool_loss = nn.functional.mse_loss(pool_outputs, pool_targets)

        predicted = threat_logits.argmax(dim=-1)
        accuracy = float((predicted == threat_targets).float().mean().item())
        mae = float((pool_outputs - pool_targets).abs().mean().item())

    return {
        "loss": float((threat_loss + pool_loss_weight * pool_loss).item()),
        "threat_loss": float(threat_loss.item()),
        "pool_loss": float(pool_loss.item()),
        "threat_accuracy": accuracy,
        "threat_balanced_accuracy": balanced_accuracy(predicted, threat_targets),
        "pool_mae": mae,
    }


def majority_class_accuracy(threat_targets: torch.Tensor) -> float:
    """The rate a constant predictor would achieve -- the bar the threat
    head has to clear before its accuracy means anything."""
    values, counts = torch.unique(threat_targets, return_counts=True)
    return float(counts.max().item() / threat_targets.numel())


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the dual-head LSTM forecaster.")
    parser.add_argument("--epochs", type=int, default=12)
    parser.add_argument("--rollout-steps", type=int, default=1200)
    parser.add_argument("--seeds", type=int, default=2)
    parser.add_argument("--out", type=str, default=DEFAULT_CHECKPOINT)
    args = parser.parse_args()

    train_forecaster(
        epochs=args.epochs,
        rollout_steps=args.rollout_steps,
        rollout_seeds=tuple(range(args.seeds)),
        checkpoint_path=args.out,
    )


if __name__ == "__main__":
    main()
